name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: ["3.11", "3.x"]

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Pytest
        run: |
          pytest
